version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: log-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aniketh
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: log-pulse
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  